# airの設定ファイル

[build]
# 出力されるバイナリファイル
bin = "bin/main" 
cmd = "go build -gcflags=\"all=-N -l\" -o ./bin/main ."
full_bin = "dlv --headless=true --listen=:40000 --api-version=2 --accept-multiclient exec --continue ./bin/main"

[watch]
# 監視するディレクトリ
includes = ["."]